name: Banner Update
on:
  workflow_dispatch: {}
#   schedule:
#       - cron: '* * 5 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@v2
          with:
            node-version: '17'
          env:
            NODE_ENV: production
            BACKGROUND_IMAGE: ${{ secrets.BACKGROUND_IMAGE }}
            STYLESHEET_NAME: ${{ secrets.STYLESHEET_NAME }}
            NO_FOLLOWERS: ${{ secrets.NO_FOLLOWERS }}
            TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
            TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
            TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
            TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
            TWITTER_TOKEN_SECRET: ${{ secrets.TWITTER_TOKEN_SECRET }}
            IMAGES_CONTAINER_ID: ${{ secrets.IMAGES_CONTAINER_ID }}
        - run: npm install
        - run: node src/twitter-banner.js
