name: Banner Update
on:
  workflow_dispatch: {}
  schedule:
      - cron: '* * 5 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@v2
          with:
            node-version: '17'
        - run: npm install
        - run: node src/twitter-banner.js
